# Generated by Django 5.1.7 on 2025-03-20 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='current_version',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Version', 'verbose_name_plural': 'Versions'},
        ),
        migrations.AddField(
            model_name='company',
            name='id_current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.current_version'),
        ),
    ]
