# Generated by Django 5.1.7 on 2025-03-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0005_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice number')),
                ('date_sale', models.DateField(verbose_name='Date of sale')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total & Taxes')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='State')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('deleted', models.BooleanField(default=False)),
                ('id_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date_sale'],
            },
        ),
        migrations.CreateModel(
            name='Invoicedetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice detail identifier')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('total_taxes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total & Taxes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('deleted', models.BooleanField(default=False)),
                ('id_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Invoice number')),
                ('id_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product identifier')),
            ],
            options={
                'verbose_name': 'Invoice detail',
                'verbose_name_plural': 'Invoice details',
                'ordering': ['-id_invoice'],
            },
        ),
    ]
