# Generated by Django 5.1.7 on 2025-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Quantity'),
        ),
    ]
