# Generated by Django 5.1.7 on 2025-03-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_bill_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='correct_billing_info',
            field=models.BooleanField(default=False),
        ),
    ]
